# Generated by Django 4.1 on 2022-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default='2020-08-21'),
            preserve_default=False,
        ),
    ]
