# Generated by Django 4.1 on 2022-08-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
    ]
